image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - before: bash .gp/bash/before-tasks.sh
    init: |
      bash .gp/bash/init-gitpod.sh
      bash .gp/bash/init-optional-scaffolding.sh
      bash .gp/bash/init-project.sh
      bash .gp/bash/init-complete.sh
    name: Main Terminal
  - openMode: split-right
    command: |
      bash .gp/bash/start-server.sh
    name: Web Server
  - openMode: split-right
    command: |
      if bash .gp/bash/open-preview.sh; then exit; else bash .gp/bash/patch-preview.sh; fi
    name: Extra Terminal

vscode:
  extensions:
    - felixfbecker.php-debug
